name: "Bug Report"
description: Create a new ticket for a bug.
title: "[BUG] - <title>"
labels: [
  "bug"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description of your issue
      render: bash
    validations:
      required: true    
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Copy and paste relevant log output with Debug mode enabled (log level).
      render: bash
      placeholder: Clear any tokens or sensitive data before submitting.
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: "OS"
      description: What is the impacted environment?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
        - Other
    validations:
      required: false
